services:

  server:
    build:
      context: .
    ports:
      - 80:80
    environment:
      SERVER_PORT: 80
      DB_URL: jdbc:mysql://database:3306/tech_sprint_solutions_db_dev
      DB_USER: mysql
      DB_PASSWORD: password
      DB_DRIVER_CLASS: com.mysql.cj.jdbc.Driver
      DB_TIMEOUT: 30000
      DB_MAXIMUM_POOL_SIZE: 3
      DB_DDL_AUTO: update
      DB_OPEN_VIEW: false
      SPRING_SECURITY_JWT_SIGNATURE: CCgbVvfCkAx884yCIadHEOSiO3wOw3AY1OCFvXgwD2TNTxDgTuXi3OrDaH4rzEGS0J6gynpO8K13nT70pbAaDGQdhEOk8G6JRtdz
      SPRING_PROFILES_ACTIVE: dev
      SERVER_SERVLET_CONTEXT_PATH: /tech-sprint-solutions
      SPRING_DOC_ACTUATOR: true
      JWT_PUBLIC_KEY: -----BEGIN PUBLIC KEY----- MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu0SVKnJR43L8fhAiCiYn v5qtEJfEsqIlOD/flTpcJWZlJvDh5gbbqEY6g8MSk8FArnDykB1JoUWKTYkrvzo4 Sgu6toIRDjz9peRJnmWzABqwNzP5BpAjohVCvW+8HC29Ox2PIaP9/3zxjyJZ80Jy 9yyo30s1Ocl/WWDWdqTTxdprZ4IaY4+NxiON+eJBRqwU0vT8rAMt7EwpaKe/Gzi0 iM7M9yhSaeVZq6f5+lVUlYy2r+CUtCFzqTUGmmiuc6IEZLqULzqWFnezuuUwOIZQ 1m34oq18f/8lOjOeo18b0fDO4pXn2iAjtSh3n65ItfjiwYnAXBZgFdYOau5vLuju kwIDAQAB -----END PUBLIC KEY-----
      JWT_PRIVATE_KEY: -----BEGIN PRIVATE KEY----- MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC7RJUqclHjcvx+ ECIKJie/mq0Ql8SyoiU4P9+VOlwlZmUm8OHmBtuoRjqDwxKTwUCucPKQHUmhRYpN iSu/OjhKC7q2ghEOPP2l5EmeZbMAGrA3M/kGkCOiFUK9b7wcLb07HY8ho/3/fPGP IlnzQnL3LKjfSzU5yX9ZYNZ2pNPF2mtnghpjj43GI4354kFGrBTS9PysAy3sTClo p78bOLSIzsz3KFJp5Vmrp/n6VVSVjLav4JS0IXOpNQaaaK5zogRkupQvOpYWd7O6 5TA4hlDWbfiirXx//yU6M56jXxvR8M7ilefaICO1KHefrki1+OLBicBcFmAV1g5q 7m8u6O6TAgMBAAECggEAWCun0cbmkGEcyZv98upZD6kbb/MNLRAT1yKXuhKyvPcz i/yhV6UF+foq5cvMbN3x/s/2HO11M+XigrQhcVVPmGliXTjrH9mOkXNlSBtZBqUK L8ucJb9qz48UD85ScrAEZxd5Qx0L46VntH03fcXdDEyuLAgkhNM+zw29nDnp7b6j Cxz9Xn3ByPJVWQDOSHlLCd1AeyWrABSg8hzIYMYvy7FWWxG4D0vgFlB/AUYBS9T1 IwIGmbyl209Zf9k7K32dYzSxiYzygJle55IMj4CFCkRtZPDW8axT1s5A7wJ0ctG0 zpvU3TzTZpTTumqpbBA8oDL7ZiTjUo+I9YHK8JDmSQKBgQC8XVMCQj4b10I/Ket+ /1qdCuJijrVd71oKqelw577surYEGHZp0MbB/KpT6nXRQxq/ru/FaoFYUvvwDqt8 jTaFOGcZZTaOx6PSyspwHybxNuxQq9/Fq4n5SQwdBmAuB2jrV+/gHW1/v+JA1O3b K+NPyiR0EnFIodYvRV5/18qe6QKBgQD+gnQVbPfsgfNc2OGfC5mAe7SVY/WoN4Wd UGPg0NjEJKccNF4pt4wei5Su6X9pBgp3d2vTIG5vX0GSom6fgL17xejfRRCgVO5G GwSzkR51G8mwWUfdMmNYuamhWnaUta0lsN12mzyQYAPHCVqFAQvIXf0rDyxTB85x /m8bMlVMGwKBgQCZcvlllKteKN058Z98RO//kVddbN6JWKyklUisBs69sVkIOxl0 GHVioL/tPsqeICmRUCTaUWpvlqLRLFI9VBi/LHSo9pAcfryRw0xpTKd/x/t5uJrC QH1VDFIG7yO5O6YYWvn6PF7wvFPH9u6SJs22OXm66S9KOTTwK3XRde0FyQKBgQDf le8xG2e6SHdpa8baGDCkJQkB7KzVOOGS0BrOV+r2dVSxfHf0oiDgfLMD7nFV7E6p oSoCcg1SnhZXIYeZbFoKMFViP6RZlgM1Z2r77VMagmzvFaACfM+2FHUnIPfnsKsJ 35TPK5VLKG5pHph9G+wj/B37A/tmfgcpMeKdu9wfXQKBgFVeGbsCLFVhlMIZwyE5 4W83MWVwfOOW5Xr1Ax6hCfEG+41It3yW/v0uXplmevrQ3HkhnBxcAhPhwDwLHI9y Bt/Y+fxLHaMruYFsF2zgDAQgZjxV3m1lE6yAGNuErrJh0AMTokA8m5JDjKoXgqQi QG//w3HdovgMpjQBwzuco2ML -----END PRIVATE KEY-----

  database:
    container_name: database
    image: bitnami/mysql:8.0.26-debian-10-r60
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: mysql
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./src/main/docker/create_databases.sql:/docker-entrypoint-initdb.d/init.sql